<a href="https://colab.research.google.com/github/ClarisseAlvarenga/data_science_alura_cursos/blob/master/Python_Data_Science_Numpy_curso_Alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [1]:
!python -V

Python 3.6.9


# 1.3 Trabalhando com arrays Numpy

In [2]:
#importando a biblioteca
import numpy as np

In [3]:
#puxando dados de um arquivo de texto para um array do Numpy
km = np.loadtxt('/content/carros-km.txt')


In [4]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [5]:
#puxando os dados do arquivo txt e definindo o tipo de variável como inteiro
anos = np.loadtxt('/content/carros-anos.txt', dtype= int)

In [6]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtendo a quilometragem média por ano

In [7]:
#fazendo o cálculo direto em todo o array
km_media = km/(2020 - anos)

In [8]:
km_media

array([2.61235294e+03, 1.96965517e+02, 1.23743333e+03, 0.00000000e+00,
       1.83978571e+03, 1.34100000e+03, 0.00000000e+00, 7.05445455e+03,
       9.91970000e+03, 4.21977778e+03, 7.14388889e+02, 6.19384615e+02,
       4.72489474e+03, 0.00000000e+00, 3.76881818e+03, 2.89017500e+04,
       5.80612500e+03, 0.00000000e+00, 9.27150000e+03, 5.05766667e+03,
       5.62183333e+03, 0.00000000e+00, 3.77226923e+03, 3.55031034e+03,
       0.00000000e+00, 0.00000000e+00, 1.44875000e+03, 0.00000000e+00,
       3.26933333e+03, 3.25451724e+03, 1.31143478e+03, 2.13328000e+03,
       8.86000000e+03, 1.16579310e+03, 1.51140000e+04, 1.75900000e+03,
       0.00000000e+00, 0.00000000e+00, 5.02363636e+02, 0.00000000e+00,
       1.33450000e+04, 2.39776471e+03, 0.00000000e+00, 4.79455556e+03,
       0.00000000e+00, 5.41944444e+02, 4.37156250e+03, 1.26052632e+02,
       0.00000000e+00, 4.72641176e+03, 7.77763636e+03, 3.60685714e+03,
       3.38580000e+03, 6.71050000e+03, 3.53450000e+03, 3.11565385e+03,
      

In [9]:
type(km_media)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [10]:
2 + 2

4

### Subtração ($-$)

In [11]:
2 - 2

0

### Multiplicação ($*$)

In [12]:
2 * 3

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [13]:
10 /3

3.3333333333333335

In [14]:
#a // mostra apenas o inteiro de uma divisão
10 //3

3

### Exponenciação ($**$)

In [15]:
2 **3

8

### Resto da divisão ($\%$)

In [16]:
10 % 3

1

In [17]:
#na divisão exata retorna 0
10 % 2

0

### Expressões matemáticas

In [18]:
# fará o cálculo conforme a regra matemática (primeiro a multiplicação, depois a adição)
5 * 2 + 3 * 2

16

In [19]:
#podemos usar parênteses para alterar a ordem padrão de cálculo

In [20]:
5*(2+3)*2

50

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [21]:
#funciona como a memória numa calculadora - exemplo
_

50

In [22]:
5*2

10

In [23]:
_ + 3*2

16

**Exercicio:**
Considere as expressões abaixo:

1) 10 % 2 + 3 // 10

2) 5 * (2 + 3) / 2

3) 2 ** 3 * 4

Selecione a alternativa que apresenta os resultados corretos de cada uma das expressões acima, utilizando a linguagem Python.

In [24]:
10 % 2 + 3 // 10

0

In [25]:
5 * (2 + 3) / 2

12.5

In [26]:
2 ** 3 * 4

32

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável /nome_da_variavel / NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [27]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0 #usamos o zero após o ponto para setar a variável como float

In [28]:
#visualizando as variáveis
ano_atual

2019

In [29]:
ano_fabricacao

2003

In [30]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [31]:
#fazendo o mesmo cálculo do início mas usando as variáveis criadas ao invés do array
km_media = km_total/(ano_atual - ano_fabricacao)

In [32]:
km_media

2775.625

In [33]:
km_total = km_total + km_media

In [34]:
km_total

47185.625

In [35]:
#usando o operador +=
km_total += km_media
km_total

49961.25

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [36]:
#criando várias variáveis ao mesmo tempo
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0

In [37]:
ano_atual

2019

In [38]:
ano_fabricacao

2003

In [39]:
km_total

44410.0

In [40]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0
km_media = km_total/(ano_atual - ano_fabricacao)
km_media

2775.625

**Exercício**:

Avalie os itens abaixo:

1)

A = 1

B = 2

C = 3

É equivalente a:

A, B, C = 1, 2, 3


2)

soma = soma + valor

É equivalente a:

soma += valor

3)

quadrado = valor ** 2

É equivalente a:

quadrado **= 2

Quais estão corretos?

In [41]:
#a primeira e a segunda estão corretas, mas vamos colocar todas no notebook para fixação
#criando variáveis:
A,B, C = 1,2,3
soma = (A + B + C)
valor = C

In [42]:
print (A, B, C)
print (soma)
print (valor)

1 2 3
6
3


In [43]:
soma += valor
soma

9

In [44]:
quadrado = valor**2
quadrado

9

In [45]:
#apesar de retornar um 
quadrado = 9
quadrado **=2
quadrado

81

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [46]:
type(ano_atual)

int

In [47]:
type(km_total)

float

### Booleanos

In [48]:
zero_km = True

In [49]:
type(zero_km)

bool

In [50]:
zero_km = False

In [51]:
type(zero_km)

bool

### Strings

In [52]:
nome = 'Jetta Variant'

In [53]:
type(nome)

str

In [54]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [55]:
#usando citações - podemos usar as aspas duplas dentro das simpes
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [56]:
#ou aspas simples dentro das duplas
nome = "Jetta 'Variant'"
nome

"Jetta 'Variant'"

In [57]:
#usando três aspas para criar um texto (''' texto ''')
carro = '''
  Nome
  Idade
  Nota
  Ano

'''
carro

'\n  Nome\n  Idade\n  Nota\n  Ano\n\n'

In [58]:
type(carro)

str

### None

In [59]:
quilometragem = None

In [60]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [61]:
#criando variáveis
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [62]:
type(a)

int

In [63]:
type(b)

int

In [64]:
type(c)

str

In [65]:
type(d)

str

In [66]:
a + b

30

In [67]:
c + d

'Python é legal'

In [68]:
#transformando o 10 em string
c + str(a)

'Python é 10'

### Conversões de tipo

Funções int(), float(), str()

In [69]:
str(a)

'10'

In [70]:
type(str(a))

str

In [71]:
#tranformar em float
float(a)

10.0

In [72]:
var = 3.141592
type(var)

float

In [73]:
#o int não arredonda, ele pega apenas a parte inteira, ignorando o decimal.
int(var)

3

In [74]:
#demonstrando:
var_float = 3.99999999999
int(var_float)

3

**Exercício**



Assinale a alternativa que produz o seguinte output no console do Colab:

'A quilometragem média do veículo é 5000 km'

In [75]:
#variáveis do problema
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999
#resolução do problema (usando a concatenação e duas conversões (transforma um float em int e depois em string))
text + str( int( Km / (Ano_atual - Ano_fabricacao) ) ) + ' km'

'A quilometragem média do veículo é 5000 km'

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [76]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [77]:
# Isto é um comentário
# Ctrl ; faz o toggle do comentário
ano_atual = 2019
ano_atual

2019

In [78]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [79]:
'''Isto é um
comentário''' 
ano_atual = 2019
ano_atual

2019

In [80]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [81]:
#exemplo da documentação
print('%(language)s has %(number)03d quote types.' %
      {'language': "Python", "number": 2})

Python has 002 quote types.


In [82]:
#tentando fazer criando as variáveis antes
language = 'JavaScript'
number = 5
print('%(language)s has %(number)03d quote types.'%{'language': language, 'number':number})

JavaScript has 005 quote types.


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [83]:
print('Olar, {}!'.format('Rodrigo')) #dentro do format vai o parâmetro passado pra a string

Olar, Rodrigo!


In [84]:
print('Olá, {}! Este é seu acesso de número {}'.format('Rodrigo', 32)) #estes parâmetros são posicionais caso não nomeados

Olá, Rodrigo! Este é seu acesso de número 32


In [85]:
#criando as variáveis dentro do format, não é mais necessariamente posicional
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(acessos = 32, nome='Rodrigo'))

Olá, Rodrigo! Este é seu acesso de número 32


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [86]:
acessos, nome = 32, 'Rodrigo'
print(f'Olá {nome}! Este é seu acesso de número {acessos}')

Olá Rodrigo! Este é seu acesso de número 32


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [87]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [88]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [89]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [90]:
#a lista conta como um elemento de outra lista
len(Carro_1)

7

In [91]:
Carros = [Carro_1, Carro_2]

In [92]:
#uma lista de listas
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [93]:
#identifica se um item está dentro da lista. Vamos varrer uma lista e ver se possuem uma característica específica
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [94]:
'Rodas de liga' in Acessorios

True

In [95]:
'4 X 4' in Acessorios

False

In [96]:
#podemos fazer a pergunta contrária
'Rodas de liga' not in Acessorios

False

In [97]:
'4 X 4' not in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [98]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [99]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [100]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [101]:
#concatenando as listas
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [102]:
len(A)

4

**Exercício**



In [103]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [104]:
'2003' in carro

False

In [105]:
'Rodas de liga' in carro

False

In [106]:
'False' not in carro

True

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [107]:
#acessando o primeiro item da lista
Acessorios[0]

'Rodas de liga'

In [108]:
#acessando o último item da lista
Acessorios[-1]

'Sensor de chuva'

In [109]:
#fazendo pesquisas em listas dentro de listas
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [110]:
#acessando o primeiro item da primeira lista
Carros[0][0]

'Jetta Variant'

In [111]:
#acessando uma lista dentro de uma lista dentro de outra lista
Carros[0][-2][1]

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [112]:
Acessorios[2:7]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular']

In [113]:
#buscando todos os itens da lista a partir do segundo
Acessorios[1:]

['Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [114]:
#buscando do primeiro até o terceiro item da lista
Acessorios[:3]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

**Exercício**

In [115]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [116]:
letras[:2]

['A', 'B']

In [117]:
letras[2:5]

['C', 'D', 'E']

In [118]:
letras[-3:]

['F', 'G', 'H']

**Exercício**

1) True

2) 'Teto panorâmico'

3) ['Rodas de liga', 'Travas elétricas', 'Piloto automático']

Busque os itens acima na lista abaixo

In [119]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

In [120]:
carros[1][-2]

True

In [121]:
carros[-1][-1][-2]

'Teto panorâmico'

In [122]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [123]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [124]:
#altera a lista
Acessorios.sort()

In [125]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [126]:
Acessorios.append('4 X 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [127]:
Acessorios.pop()

'4 X 4'

In [128]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [129]:
#remover um item específico a partir do index
Acessorios.pop(3)

'Rodas de liga'

In [130]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [131]:
#as alterações em Acessorios_2 vão afetar o Acessorios
Acessorios_2 = Acessorios

In [132]:
Acessorios_2 = Acessorios.copy()

In [133]:
Acessorios_2.append('4 x 4')

In [134]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [135]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [136]:
#podemos ainda criar um novo usando uma seleção de slice completa
Acessorios_3 = Acessorios_2[:]

In [137]:
Acessorios_3.pop()

'4 x 4'

In [138]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [139]:
Acessorios_3

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

**Exercício**


In [1]:

Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

In [2]: Qual código?


Out [2]: ['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

 
Assinale a alternativa que apresenta o código executado na célula In [2].

In [140]:
Acessorios = [ 'Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado' ]

In [141]:
Acessorios.append('Airbag')
Acessorios.append('Vidros Elétricos')
Acessorios.pop(1)
Acessorios.sort()
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros Elétricos']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [142]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [143]:
for item in Acessorios:
  print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [144]:
#crie um iterador de tamanho 10
range(10)

range(0, 10)

In [145]:
#rodando um for usando o range
for i in range(10):
  print(i **2)

0
1
4
9
16
25
36
49
64
81


In [146]:
#criando uma lista com range
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [147]:
#alimentando uma lista criada previamente usando o for e o range
quadrado = []
for i in range(10):
  quadrado.append(i**2)
print(quadrado)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [148]:
#fazendo a mesma coisa da lista anterior em uma linha de código
#[instrução FOR variável in range(tamanho)]
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [149]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [150]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [151]:
#for aninhado
for lista in dados:
  for item in lista:
    print(item)


Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [152]:
#pegar apenas os itens únicos
Acessorios = []
for lista in dados:
  for item in lista:
    Acessorios.append(item)
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [153]:
#usando o set para remover os itens duplicados e retransformando em lista
list(set(Acessorios))

['4 X 4',
 'Freios ABS',
 'Bancos de couro',
 'Central multimídia',
 'Travas elétricas',
 'Sensor crepuscular',
 'Piloto automático',
 'Rodas de liga',
 'Controle de estabilidade',
 'Painel digital',
 'Câmera de estacionamento',
 'Sensor de estacionamento',
 'Vidros elétricos',
 'Sensor de chuva',
 'Ar condicionado',
 'Câmbio automático',
 'Teto panorâmico']

### List comprehensions

In [154]:
#usando list comprehension para fazer a mesma coisa do código com os for aninhados
list(set([item for lista in dados for item in lista]))

['4 X 4',
 'Freios ABS',
 'Bancos de couro',
 'Central multimídia',
 'Travas elétricas',
 'Sensor crepuscular',
 'Piloto automático',
 'Rodas de liga',
 'Controle de estabilidade',
 'Painel digital',
 'Câmera de estacionamento',
 'Sensor de estacionamento',
 'Vidros elétricos',
 'Sensor de chuva',
 'Ar condicionado',
 'Câmbio automático',
 'Teto panorâmico']

**Exercício**

In [155]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [156]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [157]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [158]:
[item for lista in dados for item in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [159]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [160]:
zero_km_Y = []
for lista in dados:
  if (lista[-1] == True):
    zero_km_Y.append(lista)
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [161]:
zero_km_N = []
for lista in dados:
  if (lista[-1] != True):
    zero_km_N.append(lista)
zero_km_N


[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### List comprehensions

In [162]:
#usando list comprehension para um for com um condicional
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [163]:
#exercício - fazer a mesma coisa para o False
[lista for lista in dados if lista[2] != True]


[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [164]:
#usando o exemplo anterior, só mudando a estrutura para if e else
zero_km_Y, zero_km_N = [],[]
for lista in dados:
  if (lista[-1] == True):
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)

In [165]:
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [166]:
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [167]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [168]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [169]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [170]:
A, B, C = [],[],[]
for lista in dados:
  if(lista[1] <= 2000):
    A.append(lista)
  elif(lista[1] > 2000 and lista[1]<= 2010):
    B.append(lista)
  else:
    C.append(lista)


In [171]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [172]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [173]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [174]:
A, B, C = [],[],[]
for lista in dados:
  if(lista[1] <= 2000):
    A.append(lista)
  elif( 2000 < lista[1] <= 2010): #isto algumas linguagens não aceitam, mas é possível no python.
    B.append(lista)
  else:
    C.append(lista)
print(A)
print(B)
print(C)

[['Passat', 1991, False], ['Crossfox', 1990, False]]
[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]
[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [175]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [176]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [177]:
import numpy as np

In [178]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [179]:
from numpy import arange

In [180]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [181]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [182]:
km = np.array([1000,2300,4987,1500])

In [183]:
km

array([1000, 2300, 4987, 1500])

In [184]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [185]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [186]:
#aqui podemos definir o tipo de variável que queremos no array
km = np.loadtxt(fname='carros-km.txt', dtype=int)

In [187]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

### Arrays com duas dimensões

In [188]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [189]:
Acessorios = np.array(dados)

In [190]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [191]:
km.shape

(258,)

In [192]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [193]:
np_array = np.arange(1000000)

In [194]:
py_list = list(range(1000000))

In [195]:
# o %time é usado para testar o tempo de resposta
%time for _ in range(100): np_array *=2

CPU times: user 70 ms, sys: 0 ns, total: 70 ms
Wall time: 73.8 ms


In [196]:
# o %time é usado para testar o tempo de resposta
%time for _ in range(100): py_list =[x*2 for x in py_list]

CPU times: user 7.6 s, sys: 1.62 s, total: 9.22 s
Wall time: 9.34 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [197]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [198]:
# idade = 2019 - anos

In [199]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [200]:
idade = 2019 - anos

In [201]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [202]:
km_media = km/idade

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [203]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [204]:
44410 /(2019-2003)

2775.625

### Operações com arrays de duas dimensões

In [205]:
dados = np.array([km, anos])

In [206]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [207]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [208]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [209]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [210]:
km_media = dados[0] /(2019 - dados[1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [211]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [214]:
dados[0][0]

44410.0

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [215]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
contador[0]

0

In [218]:
item = 6
index = item -1
contador[index]

5

In [219]:
contador[-1]

9

In [220]:
dados[0][3]

0.0

In [221]:
dados[1,2]

1990.0

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [222]:
dados[0,4]

25757.0

In [223]:
dados[0][4]

25757.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [224]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
contador[1:4]

array([1, 2, 3])

In [227]:
#incluindo o passo
contador[1:8:2]

array([1, 3, 5, 7])

In [228]:
#pegando os pares
contador[::2]

array([0, 2, 4, 6, 8])

In [229]:
#pegando os ímpares
contador[1::2]

array([1, 3, 5, 7, 9])

In [231]:
#varrendo todas as linhas e dois veículos
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [233]:
#calculando kilometragem média
dados[:, 1:3][0]/(2019-dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [234]:
contador >5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [235]:
#fazendo um slice com um booleano
contador[contador>5]

array([6, 7, 8, 9])

In [236]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [237]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [240]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [241]:
dados[:, dados[1] > 2000][0]/ (2019 - dados[:, dados[1] > 2000][1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,           nan, 1981.30769231])

**Exercício**

In [242]:
dados_ex = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

In [243]:
dados_ex

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteiro', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casado', 'feminino']], dtype='<U9')

In [247]:
dados_ex[::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [248]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [250]:
#linhas, colunas
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [251]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [252]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [253]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [254]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [256]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [257]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [258]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
#muda o formato do array (informando linhas e colunas numa tupla, por exemplo)
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [260]:
#buscando a ordem baseada na linguagem C
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [261]:
#usando Fortran como ordenador
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [264]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [269]:
#concatenando listas
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [270]:
#criando o array já com o reshape
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [271]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [274]:
dados_new.resize((3,5), refcheck=False)

In [275]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [276]:
dados_new[2] = dados_new[0]/(2019 - dados_new[1])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [277]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [278]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [279]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [281]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [282]:
dataset.shape

(258, 3)


## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [283]:
#fez a média de todos os elementos do array
np.mean(dataset)

48489.14648578811

In [285]:
#media por colunas
np.mean(dataset, axis=0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [286]:
#media por linha
np.mean(dados, axis=1)

array([22600.4,  2001.8])

In [290]:
#fazendo a média de colunas específicas de um dataset
np.mean(dataset[:,2])

44499.41472868217

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [291]:
np.std(dataset[:,2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [292]:
#assim soma todos os elementos
dataset.sum()

37530599.379999995

In [293]:
#por coluna
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [295]:
#por slice
dataset[:,1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [296]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [297]:
np.sum(dataset[:,2])

25531812.38